### PR TITLE
hello microverse

### PR DESCRIPTION
**Pull request by techmoves**
In this PR this are the things i did

- [x] A .html file that includes a header with the text "Hello Microverse!". 
- [x] A .css file  includes one class with styles for your header 
- [x] A test.md file with the text "This file should be ignored by git".
- [x] made with css and html one
- [x] no linters error

### CODE REVIEW

**Review by DuaneDave — CHANGES_REQUESTED** [review]
Hi @techmoves 👋 , 

Good job so far on this project!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
✔️ All linter checks are green.
✔️ Correct Github flow
✔️ Very professional and organized readme

## Required Changes ♻️
- Consider adding a link to your Twitter and GitHub handles to make it easy for your project followers to connect with you instead of just writing your username. 

no link

- I recommend you update your PR summary as it is not descriptive enough. Instead of writing the project title, you should have added the changes you have made in the milestone. This would make it easier for your code reviewers to tell what you are submitting for or the changes you have made. 

For example: 
    - Add linters to the project.
    - Add a custom HTML and CSS file.
    - Add a test.md file
    - Add a gitignore file.
   
notDesc

In order to edit the PR, try clicking on the buttons circled blue

- Although the project isn't deployed, it is still important for you to have the deployment section. You could add 'project not deployed yet' instead of removing the section. 

nodeployment

- To make the readme more professional it is expected that the MIT link leads to the project license but when I click the link, it directs me to a 404 page instead of the actual license file. You can fix this by changing the link to ./LICENSE 

FIXmit

WHAT I GET WHEN THE PROVIDED LINK IS CLICKED.
nomit


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- Starting off a commit message with a capital letter in order to follow best practices

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by techmoves** [comment]
hi made some changes can you review it again

**Review by Shisui6 — CHANGES_REQUESTED** [review]
Hi @techmoves, 

# Requires Changes 🍀
Great work on making the changes requested by a previous reviewer 👍
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet🪲.


 ## Highlights
 - Descriptive PR title and summary ✅
 - Follows Github flow ✅
 - Good commit messages ✅

 ## Required Changes ♻️

- Good job adding your MIT license👍. However, you removed the link to it from your readme file as seen in the screenshot below:

image

Please replace the `Note:` with the link to your license 


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code. Some of them were simply missed by the previous reviewer, and addressing them will really improve your application._

You can also consider the following:

N/A

Cheers and Happy coding!🍻💻

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid, unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561), you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by techmoves** [comment]
hi  [Shisui6](https://github.com/Shisui6)

the link is removed

**Comment by techmoves** [comment]
RemovedSent from my phone-------- Original message --------From: Okemdi Udeh ***@***.***>Date: Mon, 20 Feb 2023, 19:35To: techmoves/hello-microverse1 ***@***.***>Cc: Phelelani Ndlovu ***@***.***>, Mention ***@***.***>Subject: Re: [techmoves/hello-microverse1] hello microverse (PR #1)

@Shisui6 requested changes on this pull request.



Hi @techmoves,

Requires Changes 🍀

Great work on making the changes requested by a previous reviewer 👍

You've done well implementing some of the requested changes, but there are still some which aren't addressed yet🪲.

Highlights

Descriptive PR title and summary ✅Follows Github flow ✅Good commit messages ✅

Required Changes ♻️

Good job adding your MIT license👍. However, you removed the link to it from your readme file as seen in the screenshot below:



Please replace the Note: with the link to your license

Optional suggestions

Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code. Some of them were simply missed by the previous reviewer, and addressing them will really improve your application.

You can also consider the following:

N/A

Cheers and Happy coding!🍻💻

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

Please, remember to tag me in your question so I can receive the notification.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid, unless it is requested otherwise.



As described in the Code reviews limits policy, you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using this form.

**Review by DuaneDave — APPROVED** [review]
Hi @techmoves 👋, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
✔️ All linter checks are green.
✔️ Correct Github flow
✔️ Very professional and organized readme

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by shella12 — COMMENTED** [review]
Hi @techmoves, 


## Status : APPROVED 🥳 🥳 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



## Highlights

- Linters are passing ✔️ 
- Implemented all requirements 👏 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
